// <auto-generated />

using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Markup.Xaml;
using Spreadsheet_Brandon_Xu.ViewModels;
using Spreadsheet_Brandon_Xu.Views;

namespace Spreadsheet_Brandon_Xu;

/// <inheritdoc />
public partial class App : Application
{
    /// <summary>Initializes the application by loading XAML etc.</summary>
    public override void Initialize()
    {
        AvaloniaXamlLoader.Load(this);
    }

    /// <inheritdoc />
    public override void OnFrameworkInitializationCompleted()
    {
        if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            desktop.MainWindow = new MainWindow
            {
                DataContext = new MainWindowViewModel(),
            };
        }

        base.OnFrameworkInitializationCompleted();
    }
}